#!/bin/sh

git_cache() {
    git -C "${GIT_CACHE}" $*
}

init() {
    set -ex
    test -d "${GIT_CACHE}/.git" || {
        mkdir -p "${GIT_CACHE}"

        git_cache init --bare
        git_cache config core.compression 1
    }
    set +ex
}

add() {
    set -ex
    git_cache remote add $1 $2
    set +ex
}

update() {
    set -ex
    REMOTE=${1:---all}
    git_cache fetch $REMOTE
    set +ex
}

list() {
    REMOTES="$(git_cache remote show)"
    for remote in $REMOTES; do
        echo "${remote}: $(git_cache remote get-url $remote)"
    done
}

drop() {
    set -ex
    REMOTE=${1}
    [ -z "$REMOTE" ] && {
        echo "usage: git cache drop <name>"
        exit 1
    }
    git_cache remote remove $REMOTE
    set +ex
}

usage() {
    echo "git cache uses a bare git repository containing all objects from multiple"
    echo "upstream git repositories."
    echo ""
    echo "usage:"
    echo ""
    echo "    git cache init                initialize git cache"
    echo "    git cache add <name> <url>    add repository <url> with name <name>"
    echo "    git cache list                list cached repositories"
    echo "    git cache drop <name>         drop repo from cache"
    echo "    git cache update [<name>]     fetch repo named <name> (or all)"
    echo "    git cache show-path           print's the path that can be used as "
    echo "                                  '--reference' parameter"
    echo ""
    echo "To retrieve objects from cache (will use remote repository if needed):"
    echo '    git clone --reference $(git cache show-path) <repo>'
}

ACTION=$1
shift

#GIT_CACHE=${1:-${GIT_CACHE}}
GIT_CACHE=${GIT_CACHE:-${HOME}/.gitcache}

case $ACTION in
    init)
        init $*
        ;;
    add)
        add $*
        ;;
    update)
        update $*
        ;;
    list)
        list $*
        ;;
    drop)
        drop $*
        ;;
    show-path)
        echo ${GIT_CACHE}
        ;;
    *)
        usage
        ;;
esac
